#!/usr/bin/env bash
# Never skip the real media suite: use the host tool or a digest-pinned image.
set -euo pipefail

if command -v veritysetup >/dev/null 2>&1; then
  NI_MEDIA_SUITE_REQUIRE_TOOLS=1 ./image/test-installer-media.sh
  exit 0
fi

command -v docker >/dev/null 2>&1 || {
  echo "ERROR: veritysetup is absent and the pinned validation-image runner is unavailable" >&2
  exit 1
}
image=neural-ice-media-validation:ubuntu-24.04-20260902
docker build --pull -f ci/media-validation.Containerfile -t "$image" .
# Production builders reject every test-tool override when privileged.  Run the
# validation workload as the image's unprivileged nobody identity: /src is
# deliberately read-only and every generated byte lives in its private /tmp.
docker run --rm --network=none --user 65534:65534 -v "$PWD:/src:ro" "$image" \
  'NI_MEDIA_SUITE_REQUIRE_TOOLS=1 ./image/test-installer-media.sh'
